nuplaeModule.factory("params", function (global) {

	return {

		home:{
			name:"Home",
			page:{
				back:"blue2-back",
				fore:"white-back",
				border:{
					color:"black",
					width:1,
					radius:0
				}
			}
		},
		games:[
		{
			name:"Calibrate",
			index:global.c.calibrateIndex,
			page:{
				back:"pink-back",
				fore:"white-back",
				menu:"pink-back",
				button:"transparent",
				border:{
					color:"black",
					width:1,
					radius:0
				}	
			},
			obj:{
				shape:global.c.circle,
				size:50,
				color:"black"
			},
			params:{
				interval:1/300,
				filterSize:3,
				factor:1,
				mu:0.1,
				damp:0.4,
				gravity:true,
				bounce:false
			}
		},
		{
			name:"Gravity", 
			index:global.c.gravIndex,
			page:{
				back:"green2-back",
				fore:"white-back",
				menu:"green2-back",
				button:"transparent",
				border:{
					color:"black",
					width:1,
					radius:0
				}	
			},
			obj:{
				shape:global.c.circle,
				size:50,
				color:"black"
			},
			params:{
				interval:1/300,
				filterSize:3,
				factor:1,
				mu:0.1,
				damp:0.4,
				gravity:true,
				bounce:true
			}
		},
		{
			name:"Float", 
			index:global.c.floatIndex,
			page:{
				back:"red2-back",
				fore:"white-back",
				menu:"red2-back",
				button:"transparent",
				border:{
					color:"black",
					width:1,
					radius:0
				}	
			},
			obj:{
				shape:global.c.circle,
				size:50,
				color:"black"
			},
			params:{
				interval:1/300,
				filterSize:3,
				factor:3,
				mu:0.06,
				damp:0.4,
				gravity:false,
				bounce:true
			}
		},
		{
			name:"Enemies", 
			index:global.c.enemiesIndex,
			page:{
				back:"blue2-back",
				fore:"white-back",
				menu:"blue2-back",
				button:"transparent",
				border:{
					color:"black",
					width:1,
					radius:0
				}	
			},
			obj:{
				shape:global.c.circle,
				size:50,
				color:"black"
			},
			params:{
				interval:1/300,
				filterSize:3,
				factor:1,
				mu:0.1,
				damp:0.4,
				gravity:true,
				bounce:true
			}
		},
		{
			name:"Balance", 
			index:global.c.balanceIndex,
			page:{
				back:"pink-back",
				fore:"white-back",
				menu:"pink-back",
				button:"transparent",
				border:{
					color:"black",
					width:1,
					radius:0
				}	
			},
			obj:{
				shape:global.c.circle,
				size:50,
				color:"black"
			},
			params:{
				interval:1/300,
				filterSize:2,
				factor:2,
				mu:0.1,
				damp:0.4,
				gravity:true,
				bounce:true
			}
		}
		]
	}
});